### ISSUE TITLE
How to display the UML source code?

### ISSUE THREAD

**Issue by ccworld1000** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#24]
How to display the UML source code?

**Comment by MarcoEidinger** [comment]
What do you mean? Using Xcode extension will show UML diagram in browser with respective PlantUML script

https://user-images.githubusercontent.com/4176826/224826293-2b9e7747-ebe3-46d5-a33c-f9e88452a702.mov

**Comment by ccworld1000** [comment]
Generate the source file to the local or selected directory

**Comment by ccworld1000** [comment]
Some relationships are very complex, such as complex class inheritance relationships, resulting in large data or large drawing. If this optimization option can be provided, it may reduce the drawing of beams or drawing area or drawing size, and the description may not be very appropriate.

**Comment by MarcoEidinger** [comment]
So the problem is that the diagram is too large to be rendered in the browser?

Try to limit the information, e.g. show elements/members only for certain access level

![](https://user-images.githubusercontent.com/4176826/150644620-19f13392-08f2-4dba-b95a-0c9a002a5272.png)

![](https://user-images.githubusercontent.com/4176826/150644626-7a566c4b-d795-432c-9a2e-ec29d2c1ba42.png)

or merge extensions instead of showing them separately in the diagram

![](https://user-images.githubusercontent.com/4176826/218329326-6953799c-faa0-4de0-93a3-9d5856587e8c.png)

If this is not helpful or not desired then please use the command-line tool SwiftPlantUML and read [this](https://github.com/MarcoEidinger/SwiftPlantUML#large-diagrams)

**Comment by ccworld1000** [comment]
In other words, there are a large number of class data structures (such as hundreds, thousands, tens of thousands, and even more) in the current actual scenario. Through Http requests, one request may have large data, and the other may return large results.

Don't know whether you can directly add the option of generating local UML source files and directly convert them locally?

**Comment by MarcoEidinger** [comment]
> In other words, there are a large number of class data structures (such as hundreds, thousands, tens of thousands, and even more) in the current actual scenario.

You are talking about evaluating many files. Then please use the command-line tool [SwiftPlantUML](https://github.com/MarcoEidinger/SwiftPlantUML)

> Don't know whether you can directly add the option of generating local UML source files and directly convert them locally?

This is possible with command-line tool SwiftPlantUML and using PlantUML to generate image locally. See [#large-diagrams](https://github.com/MarcoEidinger/SwiftPlantUML#large-diagrams) for more info.
